version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "3050:3050"
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .docker.env

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"